import { CountryInfo, Continent } from './types';

// Updated to use country codes for flagpedia.net
const generateFlagUrl = (countryCode: string): string => {
  return `https://flagpedia.net/data/flags/w580/${countryCode.toLowerCase()}.png`;
};

export const countryData: CountryInfo[] = [
  // América
  { id: 1, name: "Antigua y Barbuda", capital: "Saint John's", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("ag") },
  { id: 2, name: "Argentina", capital: "Buenos Aires", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("ar") },
  { id: 3, name: "Bahamas", capital: "Nassau", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("bs") },
  { id: 4, name: "Barbados", capital: "Bridgetown", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("bb") },
  { id: 5, name: "Belice", capital: "Belmopán", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("bz") },
  { id: 6, name: "Bolivia", capital: "Sucre", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("bo") },
  { id: 7, name: "Brasil", capital: "Brasilia", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("br") },
  { id: 8, name: "Canadá", capital: "Ottawa", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("ca") },
  { id: 9, name: "Chile", capital: "Santiago de Chile", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("cl") },
  { id: 10, name: "Colombia", capital: "Bogotá", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("co") },
  { id: 11, name: "Costa Rica", capital: "San José", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("cr") },
  { id: 12, name: "Cuba", capital: "La Habana", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("cu") },
  { id: 13, name: "Dominica", capital: "Roseau", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("dm") },
  { id: 14, name: "República Dominicana", capital: "Santo Domingo", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("do") },
  { id: 15, name: "Ecuador", capital: "Quito", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("ec") },
  { id: 16, name: "El Salvador", capital: "San Salvador", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("sv") },
  { id: 17, name: "Estados Unidos", capital: "Washington D. C.", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("us") },
  { id: 18, name: "Granada", capital: "Saint George's", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("gd") },
  { id: 19, name: "Guatemala", capital: "Ciudad de Guatemala", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("gt") },
  { id: 20, name: "Guyana", capital: "Georgetown", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("gy") },
  { id: 21, name: "Haití", capital: "Puerto Príncipe", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("ht") },
  { id: 22, name: "Honduras", capital: "Tegucigalpa", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("hn") },
  { id: 23, name: "Jamaica", capital: "Kingston", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("jm") },
  { id: 24, name: "México", capital: "Ciudad de México", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("mx") },
  { id: 25, name: "Nicaragua", capital: "Managua", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("ni") },
  { id: 26, name: "Panamá", capital: "Ciudad de Panamá", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("pa") },
  { id: 27, name: "Paraguay", capital: "Asunción", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("py") },
  { id: 28, name: "Perú", capital: "Lima", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("pe") },
  { id: 29, name: "Puerto Rico", capital: "San Juan", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("pr") },
  { id: 30, name: "San Cristóbal y Nieves", capital: "Basseterre", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("kn") },
  { id: 31, name: "Santa Lucía", capital: "Castries", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("lc") },
  { id: 32, name: "San Vicente y las Granadinas", capital: "Kingstown", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("vc") },
  { id: 33, name: "Surinam", capital: "Paramaribo", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("sr") },
  { id: 34, name: "Trinidad y Tobago", capital: "Puerto España", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("tt") },
  { id: 35, name: "Uruguay", capital: "Montevideo", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("uy") },
  { id: 36, name: "Venezuela", capital: "Caracas", continent: Continent.AMERICA, flagImageUrl: generateFlagUrl("ve") },

  // Europa
  { id: 37, name: "Albania", capital: "Tirana", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("al") },
  { id: 38, name: "Alemania", capital: "Berlín", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("de") },
  { id: 39, name: "Andorra", capital: "Andorra la Vieja", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("ad") },
  { id: 40, name: "Armenia", capital: "Ereván", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("am") },
  { id: 41, name: "Austria", capital: "Viena", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("at") },
  { id: 42, name: "Azerbaiyán", capital: "Bakú", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("az") },
  { id: 43, name: "Bélgica", capital: "Bruselas", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("be") },
  { id: 44, name: "Bielorrusia", capital: "Minsk", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("by") },
  { id: 45, name: "Bosnia y Herzegovina", capital: "Sarajevo", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("ba") },
  { id: 46, name: "Bulgaria", capital: "Sofía", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("bg") },
  { id: 47, name: "República Checa", capital: "Praga", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("cz") },
  { id: 48, name: "Croacia", capital: "Zagreb", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("hr") },
  { id: 49, name: "Dinamarca", capital: "Copenhague", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("dk") },
  { id: 50, name: "Eslovaquia", capital: "Bratislava", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("sk") },
  { id: 51, name: "Eslovenia", capital: "Lublijana", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("si") },
  { id: 52, name: "España", capital: "Madrid", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("es") },
  { id: 53, name: "Estonia", capital: "Tallín", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("ee") },
  { id: 54, name: "Finlandia", capital: "Helsinki", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("fi") },
  { id: 55, name: "Francia", capital: "París", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("fr") },
  { id: 56, name: "Georgia", capital: "Tiflis", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("ge") },
  { id: 57, name: "Grecia", capital: "Atenas", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("gr") },
  { id: 58, name: "Hungría", capital: "Budapest", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("hu") },
  { id: 59, name: "Irlanda", capital: "Dublín", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("ie") },
  { id: 60, name: "Islandia", capital: "Reikiavik", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("is") },
  { id: 61, name: "Italia", capital: "Roma", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("it") },
  { id: 62, name: "Letonia", capital: "Riga", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("lv") },
  { id: 63, name: "Liechtenstein", capital: "Vaduz", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("li") },
  { id: 64, name: "Lituania", capital: "Vilna", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("lt") },
  { id: 65, name: "Luxemburgo", capital: "Luxemburgo", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("lu") },
  { id: 66, name: "Macedonia del Norte", capital: "Skopje", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("mk") },
  { id: 67, name: "Malta", capital: "La Valeta", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("mt") },
  { id: 68, name: "Moldavia", capital: "Chisinau", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("md") },
  { id: 69, name: "Mónaco", capital: "Mónaco", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("mc") },
  { id: 70, name: "Montenegro", capital: "Podgorica", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("me") },
  { id: 71, name: "Noruega", capital: "Oslo", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("no") },
  { id: 72, name: "Países Bajos", capital: "Ámsterdam", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("nl") },
  { id: 73, name: "Polonia", capital: "Varsovia", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("pl") },
  { id: 74, name: "Portugal", capital: "Lisboa", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("pt") },
  { id: 75, name: "Reino Unido", capital: "Londres", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("gb") },
  { id: 76, name: "Rumania", capital: "Bucarest", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("ro") },
  { id: 77, name: "Rusia", capital: "Moscú", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("ru") },
  { id: 78, name: "San Marino", capital: "Ciudad de San Marino", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("sm") },
  { id: 79, name: "Serbia", capital: "Belgrado", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("rs") },
  { id: 80, name: "Suecia", capital: "Estocolmo", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("se") },
  { id: 81, name: "Suiza", capital: "Berna", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("ch") },
  { id: 82, name: "Ucrania", capital: "Kiev", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("ua") },
  { id: 83, name: "Ciudad del Vaticano", capital: "Ciudad del Vaticano", continent: Continent.EUROPE, flagImageUrl: generateFlagUrl("va") },

  // Asia
  { id: 84, name: "Afganistán", capital: "Kabul", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("af") },
  { id: 85, name: "Arabia Saudita", capital: "Riad", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("sa") },
  { id: 86, name: "Baréin", capital: "Manamá", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("bh") },
  { id: 87, name: "Bangladés", capital: "Daca", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("bd") },
  { id: 88, name: "Brunei", capital: "Bandar Seri Begawan", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("bn") },
  { id: 89, name: "Bután", capital: "Timbu", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("bt") },
  { id: 90, name: "Camboya", capital: "Pnon Pehn", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("kh") },
  { id: 91, name: "Catar", capital: "Doha", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("qa") },
  { id: 92, name: "China", capital: "Pekín", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("cn") },
  { id: 93, name: "Chipre", capital: "Nicosia", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("cy") },
  { id: 94, name: "Corea del Norte", capital: "Pyongyang", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("kp") },
  { id: 95, name: "Corea del Sur", capital: "Seúl", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("kr") },
  { id: 96, name: "Emiratos Árabes Unidos", capital: "Abu Dabi", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("ae") },
  { id: 97, name: "Filipinas", capital: "Manila", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("ph") },
  { id: 98, name: "India", capital: "Nueva Delhi", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("in") },
  { id: 99, name: "Indonesia", capital: "Yakarta", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("id") },
  { id: 100, name: "Irán", capital: "Teherán", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("ir") },
  { id: 101, name: "Iraq", capital: "Bagdad", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("iq") },
  { id: 102, name: "Israel", capital: "Jerusalén", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("il") },
  { id: 103, name: "Japón", capital: "Tokio", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("jp") },
  { id: 104, name: "Jordania", capital: "Ammán", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("jo") },
  { id: 105, name: "Kazajistán", capital: "Astaná", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("kz") },
  { id: 106, name: "Kirguistán", capital: "Biskek", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("kg") },
  { id: 107, name: "Kuwait", capital: "Ciudad de Kuwait", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("kw") },
  { id: 108, name: "Laos", capital: "Vientián", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("la") },
  { id: 109, name: "Líbano", capital: "Beirut", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("lb") },
  { id: 110, name: "Malasia", capital: "Kuala Lumpur", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("my") },
  { id: 111, name: "Maldivas", capital: "Malé", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("mv") },
  { id: 112, name: "Mongolia", capital: "Ulan Bator", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("mn") },
  { id: 113, name: "Myanmar", capital: "Naypyidaw", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("mm") },
  { id: 114, name: "Nepal", capital: "Katmandú", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("np") },
  { id: 115, name: "Omán", capital: "Mascate", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("om") },
  { id: 116, name: "Pakistán", capital: "Islamabad", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("pk") },
  { id: 117, name: "Palestina", capital: "Ramala", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("ps") },
  { id: 118, name: "Singapur", capital: "Singapur", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("sg") },
  { id: 119, name: "Siria", capital: "Damasco", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("sy") },
  { id: 120, name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("lk") },
  { id: 121, name: "Tailandia", capital: "Bangkok", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("th") },
  { id: 122, name: "Taiwán", capital: "Taipéi", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("tw") },
  { id: 123, name: "Tayikistán", capital: "Dusambé", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("tj") },
  { id: 124, name: "Timor Oriental", capital: "Dili", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("tl") },
  { id: 125, name: "Turkmenistán", capital: "Asjabad", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("tm") },
  { id: 126, name: "Turquía", capital: "Ankara", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("tr") },
  { id: 127, name: "Uzbekistán", capital: "Tashkent", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("uz") },
  { id: 128, name: "Vietnam", capital: "Hanoi", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("vn") },
  { id: 129, name: "Yemen", capital: "Saná", continent: Continent.ASIA, flagImageUrl: generateFlagUrl("ye") },

  // África
  { id: 130, name: "Angola", capital: "Luanda", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ao") },
  { id: 131, name: "Argelia", capital: "Argel", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("dz") },
  { id: 132, name: "Benin", capital: "Porto-Novo", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("bj") },
  { id: 133, name: "Botsuana", capital: "Gaberones", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("bw") },
  { id: 134, name: "Burkina Faso", capital: "Uagadugú", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("bf") },
  { id: 135, name: "Burundi", capital: "Buyumbura", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("bi") },
  { id: 136, name: "Cabo Verde", capital: "Praia", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("cv") },
  { id: 137, name: "Camerún", capital: "Yaundé", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("cm") },
  { id: 138, name: "República Centroafricana", capital: "Bangui", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("cf") },
  { id: 139, name: "Chad", capital: "Yamena", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("td") },
  { id: 140, name: "Comoras", capital: "Moroni", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("km") },
  { id: 141, name: "República del Congo", capital: "Brazzaville", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("cg") },
  { id: 142, name: "República Democrática del Congo", capital: "Kinshasa", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("cd") },
  { id: 143, name: "Costa de Marfil", capital: "Yamoussoukro", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ci") },
  { id: 144, name: "Egipto", capital: "El Cairo", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("eg") },
  { id: 145, name: "Eritrea", capital: "Asmara", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("er") },
  { id: 146, name: "Etiopía", capital: "Adís Abeba", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("et") },
  { id: 147, name: "Gabón", capital: "Libreville", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ga") },
  { id: 148, name: "Gambia", capital: "Banjul", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("gm") },
  { id: 149, name: "Ghana", capital: "Accra", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("gh") },
  { id: 150, name: "Guinea", capital: "Conakry", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("gn") },
  { id: 151, name: "Guinea-Bissau", capital: "Bissau", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("gw") },
  { id: 152, name: "Guinea Ecuatorial", capital: "Malabo", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("gq") },
  { id: 153, name: "Kenia", capital: "Nairobi", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ke") },
  { id: 154, name: "Lesoto", capital: "Maseru", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ls") },
  { id: 155, name: "Liberia", capital: "Monrovia", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("lr") },
  { id: 156, name: "Libia", capital: "Trípoli", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ly") },
  { id: 157, name: "Madagascar", capital: "Antananarivo", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("mg") },
  { id: 158, name: "Malaui", capital: "Lilongüe", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("mw") },
  { id: 159, name: "Mali", capital: "Bamako", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ml") },
  { id: 160, name: "Marruecos", capital: "Rabat", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ma") },
  { id: 161, name: "Mauricio", capital: "Port Louis", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("mu") },
  { id: 162, name: "Mauritania", capital: "Nuakchot", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("mr") },
  { id: 163, name: "Mozambique", capital: "Maputo", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("mz") },
  { id: 164, name: "Namibia", capital: "Windhoek", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("na") },
  { id: 165, name: "Níger", capital: "Niamey", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ne") },
  { id: 166, name: "Nigeria", capital: "Abuya", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ng") },
  { id: 167, name: "República Saharaui", capital: "El Aaiún", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("eh") },
  { id: 168, name: "Ruanda", capital: "Kigali", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("rw") },
  { id: 169, name: "Santo Tomé y Príncipe", capital: "Santo Tomé", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("st") },
  { id: 170, name: "Senegal", capital: "Dakar", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("sn") },
  { id: 171, name: "Seychelles", capital: "Victoria", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("sc") },
  { id: 172, name: "Sierra Leona", capital: "Freetown", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("sl") },
  { id: 173, name: "Somalia", capital: "Mogadiscio", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("so") },
  { id: 174, name: "Esuatini", capital: "Mbabane", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("sz") },
  { id: 175, name: "Sudáfrica", capital: "Pretoria", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("za") },
  { id: 176, name: "Sudán", capital: "Jartum", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("sd") },
  { id: 177, name: "Sudán del Sur", capital: "Yuba", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ss") },
  { id: 178, name: "Tanzania", capital: "Dodoma", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("tz") },
  { id: 179, name: "Togo", capital: "Lomé", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("tg") },
  { id: 180, name: "Túnez", capital: "Túnez", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("tn") },
  { id: 181, name: "Uganda", capital: "Kampala", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("ug") },
  { id: 182, name: "Yibuti", capital: "Yibuti", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("dj") },
  { id: 183, name: "Zambia", capital: "Lusaka", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("zm") },
  { id: 184, name: "Zimbabue", capital: "Harare", continent: Continent.AFRICA, flagImageUrl: generateFlagUrl("zw") },

  // Oceanía
  { id: 185, name: "Australia", capital: "Canberra", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("au") },
  { id: 186, name: "Fiyi", capital: "Suva", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("fj") },
  { id: 187, name: "Kiribati", capital: "Tarawa", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("ki") },
  { id: 188, name: "Islas Marshall", capital: "Majuro", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("mh") },
  { id: 189, name: "Micronesia", capital: "Palikir", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("fm") },
  { id: 190, name: "Nauru", capital: "Yaren", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("nr") },
  { id: 191, name: "Nueva Zelanda", capital: "Wellington", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("nz") },
  { id: 192, name: "Palaos", capital: "Ngerulmud", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("pw") },
  { id: 193, name: "Papúa Nueva Guinea", capital: "Port Moresby", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("pg") },
  { id: 194, name: "Islas Salomón", capital: "Honiara", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("sb") },
  { id: 195, name: "Samoa", capital: "Apia", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("ws") },
  { id: 196, name: "Tonga", capital: "Nuku'alofa", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("to") },
  { id: 197, name: "Tuvalu", capital: "Funafuti", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("tv") },
  { id: 198, name: "Vanuatu", capital: "Port Vila", continent: Continent.OCEANIA, flagImageUrl: generateFlagUrl("vu") },
];

export const availableContinents: Continent[] = Array.from(new Set(countryData.map(c => c.continent))).sort((a, b) => {
  const order = [Continent.AMERICA, Continent.EUROPE, Continent.ASIA, Continent.AFRICA, Continent.OCEANIA];
  return order.indexOf(a) - order.indexOf(b);
});
